CREATE TABLE `coach_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(32),
	`country` varchar(64) NOT NULL,
	`city` varchar(128) NOT NULL,
	`timezone` varchar(64) NOT NULL,
	`chessTitle` varchar(32) NOT NULL,
	`currentRating` int NOT NULL,
	`ratingOrg` varchar(32) NOT NULL,
	`yearsExperience` varchar(32) NOT NULL,
	`totalStudents` int,
	`profilePhotoUrl` text,
	`certifications` text,
	`achievements` text NOT NULL,
	`specializations` text NOT NULL,
	`targetLevels` text NOT NULL,
	`teachingPhilosophy` text NOT NULL,
	`hourlyRateCents` int NOT NULL,
	`availability` text NOT NULL,
	`lessonFormats` text NOT NULL,
	`languages` text NOT NULL,
	`bio` text NOT NULL,
	`whyBoogme` text NOT NULL,
	`sampleLesson` text NOT NULL,
	`videoIntroUrl` text,
	`backgroundCheckConsent` boolean NOT NULL DEFAULT false,
	`termsAgreed` boolean NOT NULL DEFAULT false,
	`status` enum('pending','under_review','approved','rejected','withdrawn') NOT NULL DEFAULT 'pending',
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`coachProfileId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `coach_applications_id` PRIMARY KEY(`id`)
);
