CREATE TABLE `achievements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(128) NOT NULL,
	`description` text,
	`iconName` varchar(64),
	`category` enum('learning','social','streak','milestone','special'),
	`xpReward` int DEFAULT 0,
	`requirement` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `achievements_id` PRIMARY KEY(`id`)
);

CREATE TABLE `cancellations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lessonId` int NOT NULL,
	`cancelledBy` enum('student','coach') NOT NULL,
	`cancelledByUserId` int NOT NULL,
	`lessonScheduledAt` timestamp NOT NULL,
	`cancelledAt` timestamp NOT NULL DEFAULT (now()),
	`hoursBeforeLesson` int NOT NULL,
	`refundPercent` int NOT NULL,
	`refundAmountCents` int NOT NULL,
	`coachCompensationCents` int NOT NULL,
	`reason` text,
	`stripeRefundId` varchar(64),
	`refundProcessedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cancellations_id` PRIMARY KEY(`id`)
);

CREATE TABLE `coach_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(32),
	`country` varchar(64) NOT NULL,
	`city` varchar(128) NOT NULL,
	`timezone` varchar(64) NOT NULL,
	`chessTitle` varchar(32) NOT NULL,
	`currentRating` int NOT NULL,
	`ratingOrg` varchar(32) NOT NULL,
	`yearsExperience` varchar(32) NOT NULL,
	`totalStudents` int,
	`profilePhotoUrl` text,
	`certifications` text,
	`achievements` text NOT NULL,
	`specializations` text NOT NULL,
	`targetLevels` text NOT NULL,
	`teachingPhilosophy` text NOT NULL,
	`hourlyRateCents` int NOT NULL,
	`availability` text NOT NULL,
	`lessonFormats` text NOT NULL,
	`languages` text NOT NULL,
	`bio` text NOT NULL,
	`whyBoogme` text NOT NULL,
	`sampleLesson` text NOT NULL,
	`videoIntroUrl` text,
	`backgroundCheckConsent` boolean NOT NULL DEFAULT false,
	`termsAgreed` boolean NOT NULL DEFAULT false,
	`status` enum('pending','under_review','approved','rejected','withdrawn') NOT NULL DEFAULT 'pending',
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`aiVettingScore` int,
	`aiVettingDetails` text,
	`aiVettingTimestamp` timestamp,
	`autoApproved` boolean DEFAULT false,
	`humanReviewReason` text,
	`coachProfileId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `coach_applications_id` PRIMARY KEY(`id`)
);

CREATE TABLE `coach_matches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`studentId` int NOT NULL,
	`coachId` int NOT NULL,
	`overallScore` int NOT NULL,
	`styleScore` int,
	`goalScore` int,
	`scheduleScore` int,
	`communicationScore` int,
	`budgetScore` int,
	`ratingScore` int,
	`credentialScore` int,
	`experienceScore` int,
	`matchReasons` text,
	`quizAnswers` text,
	`status` enum('suggested','contacted','active','inactive') DEFAULT 'suggested',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `coach_matches_id` PRIMARY KEY(`id`),
	CONSTRAINT `uniq_coach_matches_student_coach` UNIQUE(`studentId`,`coachId`)
);

CREATE TABLE `coach_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` enum('none','CM','FM','IM','GM','WCM','WFM','WIM','WGM') DEFAULT 'none',
	`fideRating` int,
	`lichessUsername` varchar(64),
	`chesscomUsername` varchar(64),
	`specialties` text,
	`teachingStyle` enum('visual','interactive','analytical','competitive'),
	`experienceYears` int,
	`languages` text,
	`hourlyRateCents` int DEFAULT 5000,
	`currency` varchar(3) DEFAULT 'USD',
	`subscriptionTier` enum('free','growth','business') DEFAULT 'free',
	`pricingTier` enum('free','pro','elite') NOT NULL DEFAULT 'free',
	`commissionRate` int DEFAULT 12,
	`totalStudents` int DEFAULT 0,
	`totalLessons` int DEFAULT 0,
	`averageRating` decimal(3,2) DEFAULT '0.00',
	`totalReviews` int DEFAULT 0,
	`isAvailable` boolean DEFAULT true,
	`availabilitySchedule` text,
	`onboardingStep` int DEFAULT 1,
	`onboardingCompleted` boolean DEFAULT false,
	`onboardingCompletedAt` timestamp,
	`profilePhotoUrl` text,
	`videoIntroUrl` text,
	`minAdvanceHours` int DEFAULT 24,
	`maxAdvanceDays` int DEFAULT 30,
	`bufferMinutes` int DEFAULT 15,
	`lessonDurations` text,
	`lessonFormats` text,
	`packageDiscountEnabled` boolean DEFAULT false,
	`packageDiscountPercent` int DEFAULT 0,
	`guidelinesAgreed` boolean DEFAULT false,
	`guidelinesAgreedAt` timestamp,
	`profileActive` boolean DEFAULT false,
	`profileActivatedAt` timestamp,
	`isVerified` boolean DEFAULT false,
	`verifiedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `coach_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `coach_profiles_userId_unique` UNIQUE(`userId`)
);

CREATE TABLE `coach_subscription_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`coachId` int NOT NULL,
	`enabled` boolean NOT NULL DEFAULT false,
	`monthlyPriceCents` int NOT NULL DEFAULT 0,
	`description` varchar(500),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `coach_subscription_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `coach_subscription_settings_coachId_unique` UNIQUE(`coachId`)
);

CREATE TABLE `coach_subscriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`subscriberId` int NOT NULL,
	`coachId` int NOT NULL,
	`status` enum('active','cancelled','expired') NOT NULL DEFAULT 'active',
	`monthlyPriceCents` int NOT NULL DEFAULT 0,
	`stripeSubscriptionId` varchar(255),
	`currentPeriodEnd` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `coach_subscriptions_id` PRIMARY KEY(`id`),
	CONSTRAINT `coach_subscriptions_subscriberId_coachId_unique` UNIQUE(`subscriberId`,`coachId`)
);

CREATE TABLE `content_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`coachId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`kind` enum('course','video','pdf','pgn','bundle') NOT NULL,
	`storageKey` varchar(512),
	`thumbnailUrl` text,
	`priceCents` int NOT NULL DEFAULT 0,
	`currency` varchar(3) DEFAULT 'USD',
	`previewContent` text,
	`published` boolean NOT NULL DEFAULT false,
	`publishedAt` timestamp,
	`accessType` enum('public','student_only','request_fulfillment') NOT NULL DEFAULT 'public',
	`targetStudentId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `content_items_id` PRIMARY KEY(`id`)
);

CREATE TABLE `content_purchases` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contentItemId` int NOT NULL,
	`userId` int NOT NULL,
	`unlockMethod` enum('purchase','subscription','free','gift') NOT NULL,
	`amountPaidCents` int NOT NULL DEFAULT 0,
	`stripePaymentIntentId` varchar(64),
	`unlockedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `content_purchases_id` PRIMARY KEY(`id`),
	CONSTRAINT `content_purchases_stripePaymentIntentId_unique` UNIQUE(`stripePaymentIntentId`),
	CONSTRAINT `uniq_content_purchases_item_user` UNIQUE(`contentItemId`,`userId`)
);

CREATE TABLE `content_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`studentId` int NOT NULL,
	`coachId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`amountCents` int NOT NULL DEFAULT 0,
	`status` enum('queued','quoted','pending_payment','payment_collected','in_progress','delivered','cancelled','overdue') NOT NULL DEFAULT 'queued',
	`dueDate` timestamp,
	`deliveredAt` timestamp,
	`coachNote` text,
	`stripePaymentIntentId` varchar(64),
	`stripeChargeId` varchar(64),
	`stripeCheckoutSessionId` varchar(128),
	`stripeTransferId` varchar(64),
	`payoutReleasedAt` timestamp,
	`payoutAt` timestamp,
	`deadline24hReminderSentAt` timestamp,
	`deadline1hReminderSentAt` timestamp,
	`overdueNotifiedAt` timestamp,
	`contentItemId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `content_requests_id` PRIMARY KEY(`id`)
);

CREATE TABLE `disputes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lessonId` int NOT NULL,
	`studentId` int NOT NULL,
	`coachId` int NOT NULL,
	`reason` enum('coach_no_show','poor_quality','technical_issues','inappropriate_behavior','other') NOT NULL,
	`description` text NOT NULL,
	`evidence` text,
	`status` enum('pending','investigating','resolved_refund','resolved_no_refund','escalated') DEFAULT 'pending',
	`resolvedBy` int,
	`resolvedAt` timestamp,
	`resolutionNotes` text,
	`refundAmountCents` int,
	`stripeRefundId` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `disputes_id` PRIMARY KEY(`id`)
);

CREATE TABLE `group_lesson_participants` (
	`id` int AUTO_INCREMENT NOT NULL,
	`groupLessonId` int NOT NULL,
	`studentId` int NOT NULL,
	`stripePaymentIntentId` varchar(64),
	`paid` boolean NOT NULL DEFAULT false,
	`paidAt` timestamp,
	`joinedAt` timestamp NOT NULL DEFAULT (now()),
	`dropped` boolean NOT NULL DEFAULT false,
	`droppedAt` timestamp,
	CONSTRAINT `group_lesson_participants_id` PRIMARY KEY(`id`)
);

CREATE TABLE `group_lessons` (
	`id` int AUTO_INCREMENT NOT NULL,
	`coachId` int NOT NULL,
	`organizerId` int NOT NULL,
	`scheduledAt` timestamp NOT NULL,
	`durationMinutes` int NOT NULL DEFAULT 60,
	`timezone` varchar(64),
	`topic` varchar(255),
	`notes` text,
	`meetingUrl` text,
	`maxParticipants` int NOT NULL,
	`totalAmountCents` int NOT NULL,
	`perParticipantCents` int NOT NULL,
	`commissionCents` int NOT NULL,
	`coachPayoutCents` int NOT NULL,
	`currency` varchar(3) DEFAULT 'USD',
	`inviteToken` varchar(64) NOT NULL,
	`status` enum('forming','confirmed','in_progress','completed','cancelled') NOT NULL DEFAULT 'forming',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `group_lessons_id` PRIMARY KEY(`id`),
	CONSTRAINT `group_lessons_inviteToken_unique` UNIQUE(`inviteToken`)
);

CREATE TABLE `lesson_disputes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lessonId` int NOT NULL,
	`raisedBy` int NOT NULL,
	`category` enum('coach_no_show','coach_late_or_short','technical_failure','not_as_described','quality') NOT NULL,
	`description` text,
	`evidenceUrls` text,
	`status` enum('open','coach_responded','escalated','resolved') NOT NULL DEFAULT 'open',
	`coachResponse` text,
	`coachRespondedAt` timestamp,
	`coachAction` enum('accept','contest'),
	`resolution` enum('refund_full','refund_partial','denied','feedback_only'),
	`refundAmountCents` int,
	`resolvedBy` enum('coach','admin','system'),
	`resolvedAt` timestamp,
	`adminNote` text,
	`abuseFlag` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lesson_disputes_id` PRIMARY KEY(`id`),
	CONSTRAINT `lesson_disputes_lessonId_unique` UNIQUE(`lessonId`)
);

CREATE TABLE `lesson_packages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`studentId` int NOT NULL,
	`coachId` int NOT NULL,
	`totalLessons` int NOT NULL,
	`completedLessons` int DEFAULT 0,
	`remainingLessons` int NOT NULL,
	`totalAmountCents` int NOT NULL,
	`perLessonAmountCents` int NOT NULL,
	`discountPercent` int DEFAULT 0,
	`currency` varchar(3) DEFAULT 'USD',
	`stripePaymentIntentId` varchar(64),
	`status` enum('active','completed','cancelled','expired') DEFAULT 'active',
	`expiresAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lesson_packages_id` PRIMARY KEY(`id`)
);

CREATE TABLE `lessons` (
	`id` int AUTO_INCREMENT NOT NULL,
	`studentId` int NOT NULL,
	`coachId` int NOT NULL,
	`scheduledAt` timestamp NOT NULL,
	`durationMinutes` int DEFAULT 60,
	`timezone` varchar(64),
	`topic` varchar(255),
	`notes` text,
	`meetingUrl` text,
	`status` enum('pending_payment','payment_collected','pending_confirmation','confirmed','decline_pending','declined','cancel_pending','paid','in_progress','completed','released','cancelled','no_show','disputed','refunded','subscription_dm') DEFAULT 'pending_payment',
	`amountCents` int NOT NULL,
	`commissionCents` int NOT NULL,
	`coachPayoutCents` int NOT NULL,
	`currency` varchar(3) DEFAULT 'USD',
	`stripePaymentIntentId` varchar(64),
	`stripeChargeId` varchar(64),
	`stripeTransferId` varchar(64),
	`stripeCheckoutSessionId` varchar(128),
	`checkoutAttempt` int NOT NULL DEFAULT 0,
	`coachConfirmedAt` timestamp,
	`coachDeclinedAt` timestamp,
	`confirmationDeadline` timestamp,
	`studentConfirmedAt` timestamp,
	`completedAt` timestamp,
	`payoutAt` timestamp,
	`issueWindowEndsAt` timestamp,
	`refundWindowEndsAt` timestamp,
	`reminderSentAt` timestamp,
	`cancelledAt` timestamp,
	`cancelledBy` enum('student','coach','system'),
	`cancellationReason` text,
	`refundAmountCents` int,
	`refundProcessedAt` timestamp,
	`cancellationToken` varchar(64),
	`stripeReversalId` varchar(64),
	`stripeReversalAmountCents` int,
	`stripeIntendedStudentRefundCents` int,
	`stripePostPayoutRefundId` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lessons_id` PRIMARY KEY(`id`)
);

CREATE TABLE `messages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lessonId` int NOT NULL,
	`senderId` int NOT NULL,
	`contentType` enum('text','pgn') NOT NULL DEFAULT 'text',
	`content` mediumtext NOT NULL,
	`readAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `messages_id` PRIMARY KEY(`id`)
);

CREATE TABLE `notifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`type` enum('new_subscriber','new_content_request','new_message','lesson_booked','lesson_confirmed','lesson_cancelled','lesson_completed','new_review','content_delivered','content_request_quoted','content_request_declined','content_request_accepted','content_request_payment_collected','content_request_deadline_24h','content_request_deadline_1h','content_request_overdue','content_request_deadline_extended','content_request_cancelled_overdue','new_content_sale') NOT NULL,
	`title` varchar(255) NOT NULL,
	`body` text NOT NULL,
	`relatedUserId` int,
	`relatedLessonId` int,
	`relatedContentRequestId` int,
	`recipientRole` enum('coach','student') NOT NULL DEFAULT 'student',
	`readAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `notifications_id` PRIMARY KEY(`id`)
);

CREATE TABLE `payouts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`coachId` int NOT NULL,
	`lessonId` int,
	`packageId` int,
	`amountCents` int NOT NULL,
	`platformFeeCents` int NOT NULL,
	`processingFeeCents` int DEFAULT 0,
	`netAmountCents` int NOT NULL,
	`currency` varchar(3) DEFAULT 'USD',
	`stripeTransferId` varchar(64),
	`stripePayoutId` varchar(64),
	`status` enum('pending','processing','completed','failed') DEFAULT 'pending',
	`releasedAt` timestamp,
	`completedAt` timestamp,
	`failureReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `payouts_id` PRIMARY KEY(`id`)
);

CREATE TABLE `pgn_analyses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lessonId` int,
	`contentItemId` int,
	`studentId` int NOT NULL,
	`coachId` int,
	`title` varchar(255) NOT NULL,
	`originalPgn` mediumtext NOT NULL,
	`annotatedPgn` mediumtext,
	`status` enum('draft','sent') NOT NULL DEFAULT 'draft',
	`sentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pgn_analyses_id` PRIMARY KEY(`id`)
);

CREATE TABLE `referral_codes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`coachId` int NOT NULL,
	`code` varchar(12) NOT NULL,
	`isActive` boolean NOT NULL DEFAULT true,
	`totalUses` int NOT NULL DEFAULT 0,
	`maxUses` int,
	`expiresAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `referral_codes_id` PRIMARY KEY(`id`),
	CONSTRAINT `referral_codes_code_unique` UNIQUE(`code`)
);

CREATE TABLE `referrals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`referralCodeId` int NOT NULL,
	`referredUserId` int NOT NULL,
	`status` enum('signed_up','lesson_completed','reward_issued') NOT NULL DEFAULT 'signed_up',
	`rewardIssuedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `referrals_id` PRIMARY KEY(`id`),
	CONSTRAINT `referrals_referredUserId_unique` UNIQUE(`referredUserId`)
);

CREATE TABLE `reviews` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lessonId` int NOT NULL,
	`studentId` int NOT NULL,
	`coachId` int NOT NULL,
	`reviewerType` enum('student','coach') NOT NULL,
	`rating` int NOT NULL,
	`comment` text,
	`knowledgeRating` int,
	`communicationRating` int,
	`preparednessRating` int,
	`isVisible` boolean DEFAULT false,
	`visibleAt` timestamp,
	`isPublic` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `reviews_id` PRIMARY KEY(`id`)
);

CREATE TABLE `student_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`skillLevel` enum('beginner','intermediate','advanced','expert') DEFAULT 'beginner',
	`currentRating` int,
	`targetRating` int,
	`chesscomUsername` varchar(64),
	`lichessUsername` varchar(64),
	`fideId` varchar(20),
	`primaryGoal` enum('rating_improvement','tournament_prep','openings','tactics','endgames','general'),
	`playingStyle` enum('aggressive','positional','balanced','defensive'),
	`learningStyle` enum('visual','interactive','analytical','competitive'),
	`practiceSchedule` enum('casual','regular','serious','intensive'),
	`totalXp` int DEFAULT 0,
	`currentLevel` int DEFAULT 1,
	`currentStreak` int DEFAULT 0,
	`longestStreak` int DEFAULT 0,
	`assessmentData` text,
	`assessmentCompletedAt` timestamp,
	`assessmentVersion` int DEFAULT 1,
	`budgetMinCents` int,
	`budgetMaxCents` int,
	`credentialImportance` enum('gm','titled','somewhat','teaching','notimportant'),
	`improvementAreas` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `student_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `student_profiles_userId_unique` UNIQUE(`userId`)
);

CREATE TABLE `tips` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lessonId` int NOT NULL,
	`studentId` int NOT NULL,
	`coachId` int NOT NULL,
	`amountCents` int NOT NULL,
	`currency` varchar(3) DEFAULT 'USD',
	`stripeCheckoutSessionId` varchar(128),
	`stripeTransferId` varchar(64),
	`status` enum('pending','paid','transferred','failed') DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`paidAt` timestamp,
	`transferredAt` timestamp,
	CONSTRAINT `tips_id` PRIMARY KEY(`id`)
);

CREATE TABLE `user_achievements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`achievementId` int NOT NULL,
	`unlockedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `user_achievements_id` PRIMARY KEY(`id`)
);

CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64),
	`name` text,
	`email` varchar(320) NOT NULL,
	`password` varchar(255),
	`emailVerified` boolean NOT NULL DEFAULT false,
	`emailVerificationToken` varchar(64),
	`emailVerificationExpires` timestamp,
	`passwordResetToken` varchar(64),
	`passwordResetExpires` timestamp,
	`loginMethod` varchar(64),
	`role` enum('user','admin') NOT NULL DEFAULT 'user',
	`userType` enum('student','coach','both') NOT NULL DEFAULT 'student',
	`stripeCustomerId` varchar(64),
	`stripeConnectAccountId` varchar(64),
	`stripeConnectOnboarded` boolean DEFAULT false,
	`avatarUrl` text,
	`bio` text,
	`country` varchar(64),
	`timezone` varchar(64),
	`notificationPreferences` text,
	`deletedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`),
	CONSTRAINT `users_email_unique` UNIQUE(`email`)
);

CREATE TABLE `waitlist` (
	`id` int AUTO_INCREMENT NOT NULL,
	`email` varchar(320) NOT NULL,
	`name` varchar(255),
	`userType` enum('student','coach','both') DEFAULT 'student',
	`referralSource` varchar(128),
	`assessmentData` text,
	`confirmationEmailSent` boolean DEFAULT false,
	`nurtureEmail1Sent` boolean DEFAULT false,
	`nurtureEmail2Sent` boolean DEFAULT false,
	`nurtureEmail3Sent` boolean DEFAULT false,
	`nurtureEmail4Sent` boolean DEFAULT false,
	`nurtureEmail5Sent` boolean DEFAULT false,
	`lastEmailSentAt` timestamp,
	`unsubscribed` boolean DEFAULT false,
	`unsubscribedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `waitlist_id` PRIMARY KEY(`id`),
	CONSTRAINT `waitlist_email_unique` UNIQUE(`email`)
);
